apiVersion: v1
kind: Service
metadata:
  name: gorest
spec:
  selector:
    app: gorest
  ports:
    - name: http
      port: 8080

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: gorest-db
spec:
  selector:
    app: db
  ports:
    - name: http
      port: 5432
      targetPort: 5432

  type: ClusterIP 
